# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realmPractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for realmPractice
	pod 'Realm', '~> 2.8'

  target 'realmPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realmPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
